name: uitemplate
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    # MAP
  google_maps_flutter: ^2.0.2
  google_maps_flutter_web: ^0.3.0
  location: ^4.1.1
  location_web: ^3.0.0
  address_search_field: 3.1.0-nullsafety.0

  #SLIDE
  flutter_slidable: ^0.6.0

  #expand
  expand_widget: ^2.1.0

  #text
  readmore: ^2.0.0

  #COLOR
  flutter_colorpicker: ^0.4.0

  #DESIGN
  clippy_flutter: 2.0.0-nullsafety.1
  dotted_border: ^2.0.0

  #LIST
  lazy_load_scrollview: 1.3.0

  #PULL REFRESH
  pull_to_refresh: ^2.0.0

  dropdown_search: ^0.6.1

  adaptive_container:
    git:
      url: https://github.com/alnaughty/adaptive_container

  #WEB
  # hover:
  universal_html: ^2.0.8

  # Internet
  http: ^0.13.1

  # State
  provider: ^5.0.0

  #cache
  shared_preferences: ^2.0.5

  #validator
  email_validator: ^2.0.1

  #TOAST
  fluttertoast: ^8.0.6
 

  #DATE
  date_picker_timeline: ^1.2.3
  # flutter_date_picker_timeline: ^0.3.1
  intl: ^0.17.0

  flutter_localizations:
    sdk: flutter

  #GEOCODE
  google_maps_webservice: ^0.0.19

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  rxdart: ^0.26.0
  firebase_messaging: ^9.1.1
  desktop_window: ^0.4.0
  simple_animations: ^1.3.3
  file_picker: ^3.0.1
  shimmer_animation: ^2.0.0

  


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
